name: Development build

on:
  pull_request:
    branches-ignore:
      - 'l10n_main'
    types: [opened, reopened]
  push:
    branches-ignore:
      - 'l10n_main'
  workflow_dispatch:

jobs:
  build:
    name: Development build
    strategy:
      matrix:
        include:
          - platform: 2
            platform_name: ios
          - platform: 3
            platform_name: tvos
          - platform: 7
            platform_name: iossimulator
          - platform: 8
            platform_name: tvossimulator

    runs-on: macos-latest

    steps:
      - name: Remove work folders (no sudo, no secrets)
        run: |
          echo "before"
          ls -lah ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          echo "after"
          ls -lah ./

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout repository submodules
        run: git submodule update --init --recursive

      - name: Get gl4es latest commit hash
        id: gl4es-sha
        run: |
          echo "::set-output name=sha::$(git ls-remote https://github.com/PojavLauncherTeam/gl4es-114-extra refs/heads/master | grep -io '^\S*')"
        shell: bash

      - name: Cache gl4es
        uses: actions/cache@v3
        if: false
        id: gl4es-cache
        with:
          path: gl4es/libs
          key: gl4es-holy-ios-shared-2-${{ steps.gl4es-sha.outputs.sha }}

      - name: Get gl4es
        if: false && steps.gl4es-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: 'PojavLauncherTeam/gl4es-114-extra'
          path: 'gl4es'

      - name: Build gl4es
        if: false && steps.gl4es-cache.outputs.cache-hit != 'true'
        continue-on-error: true
        run: |
          cd gl4es
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          wget https://github.com/leetal/ios-cmake/raw/master/ios.toolchain.cmake
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake -DDEFAULT_ES=2 \
            -DNOX11=ON -DNOEGL=OFF -DSTATICLIB=OFF -DPLATFORM=OS64 \
            -DCMAKE_C_FLAGS=-Wno-error=implicit-function-declaration
          cmake --build build --config RelWithDebInfo --target GL
          cp -R lib/libGL.dylib ../Natives/resources/Frameworks/libgl4es_114.dylib

      - name: Download JRE8
        run: |
          mkdir -p depends
          curl -L -o depends/jre8.tar.xz https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre8-40df388/jre8-arm64-20220811-release.tar.xz
          tar -xJf depends/jre8.tar.xz -C depends/

      - name: Download JRE17
        run: |
          mkdir -p depends
          curl -L -o depends/jre17.tar.xz https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-20240121/jre17-aarch64-20240121-release.tar.xz
          tar -xJf depends/jre17.tar.xz -C depends/

      - name: Install gmake (GNU make)
        run: brew install gmake

      - name: Build for ${{ matrix.platform_name }}
        run: |
          export PATH=/usr/local/bin:$PATH
          export RUNNER=1 SLIMMED=1
          gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }}

      - name: Upload regular ipa
        uses: actions/upload-artifact@v4
        with:
          name: net.kdt.pojavlauncher-${{ matrix.platform_name }}.ipa
          path: artifacts/net.kdt.pojavlauncher-*-${{ matrix.platform_name }}.ipa

      - name: Upload slimmed ipa
        uses: actions/upload-artifact@v4
        with:
          name: net.kdt.pojavlauncher.slimmed-${{ matrix.platform_name }}.ipa
          path: artifacts/net.kdt.pojavlauncher.slimmed-*-${{ matrix.platform_name }}.ipa

      - name: Upload PojavLauncher.dSYM
        uses: actions/upload-artifact@v4
        with:
          name: PojavLauncher.dSYM
          path: artifacts/PojavLauncher.dSYM
