name: Development build

on:
  pull_request:
    branches-ignore:
      - 'l10n_main'
    types: [opened, reopened]
  push:
    branches-ignore:
      - 'l10n_main'
  workflow_dispatch:

jobs:
  build:
    name: Development build
    strategy:
      matrix:
        include:
          - platform: 2
            platform_name: ios
          - platform: 3
            platform_name: tvos
          - platform: 7
            platform_name: iossimulator
          - platform: 8
            platform_name: tvossimulator

    runs-on: macos-latest

    steps:
      - name: Remove work folders (no sudo, no secrets)
        run: |
          echo "before"
          ls -lah ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          echo "after"
          ls -lah ./

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout repository submodules
        run: git submodule update --init --recursive

      - name: Get gl4es latest commit hash
        id: gl4es-sha
        run: |
          echo "sha=$(git ls-remote https://github.com/PojavLauncherTeam/gl4es-114-extra refs/heads/master | cut -f1)" >> "$GITHUB_OUTPUT"

      - name: Download and extract JDK 8
        run: |
          mkdir -p depends
          cd depends
          curl -L -o jdk8.tar.gz https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u412-b08/OpenJDK8U-jdk_x64_mac_hotspot_8u412b08.tar.gz
          tar -xzf jdk8.tar.gz
          # Flatten directory and rename to match Makefile expectations
          INNER_DIR=$(tar -tzf jdk8.tar.gz | head -1 | cut -f1 -d"/")
          mv "$INNER_DIR" java-8-openjdk
          echo "JAVA_HOME=$(pwd)/java-8-openjdk" >> $GITHUB_ENV
          echo "$(pwd)/java-8-openjdk/bin" >> $GITHUB_PATH

      - name: Download JRE17
        run: |
          mkdir -p depends
          curl -L -o depends/jre17.tar.xz https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ca01427/jre17-arm64-20220817-release.tar.xz
          tar -xJf depends/jre17.tar.xz -C depends/

      - name: Install required tools
        run: |
          brew install make ldid wget zip cmake

      - name: Build for ${{ matrix.platform_name }}
        run: |
          export PATH=/usr/local/bin:$PATH
          export RUNNER=1
          export SLIMMED=1
          make -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }}

      - name: Upload regular ipa
        uses: actions/upload-artifact@v4
        with:
          name: net.kdt.pojavlauncher-${{ matrix.platform_name }}.ipa
          path: artifacts/net.kdt.pojavlauncher-*-${{ matrix.platform_name }}.ipa

      - name: Upload slimmed ipa
        uses: actions/upload-artifact@v4
        with:
          name: net.kdt.pojavlauncher.slimmed-${{ matrix.platform_name }}.ipa
          path: artifacts/net.kdt.pojavlauncher.slimmed-*-${{ matrix.platform_name }}.ipa

      - name: Upload PojavLauncher.dSYM
        uses: actions/upload-artifact@v4
        with:
          name: PojavLauncher.dSYM
          path: artifacts/PojavLauncher.dSYM
